### ISSUE TITLE
Please, clear default rate ('0') when rate field gets focus :)

### ISSUE THREAD

**Issue by sbondar** [bordozer/totalizator#4]
Please, clear default rate ('0') when rate input gets focus. It's boring to clear the '0' every time when I put my ideal values to rate inputs.

Thank you very much! :)

**Comment by dimasmith** [comment]
Cool! We've got an improvement request :smile: Thank you @sbondar Your request will be satisfied ASAP.

**Comment by dimasmith** [comment]
Look like it haven't been merged to public from master. Please check if it is so I can deploy it.

**Comment by dimasmith** [comment]
My bad. Merged and deployed. Enjoy (and do not forget to clean cache :smile: )
